### ISSUE TITLE
Implement Python -> COBOL Translator

### ISSUE THREAD

**Issue by MFJackH** [MFJackH/MultiPL-E#2]
As per the project [documentation](https://nuprl.github.io/MultiPL-E/new_language.html), we need to implement a translator which targets COBOL. 

Look at the examples in the `dataset_builder` folder to get started.

**Comment by MFZachS** [comment]
Possible approach:

**Deep equality**: Should be '='.

**Literal**: Translates to literal.

**Variable**: Translates to variable name.

**List**: Translates to ODO (or plain OCCURS). For example, for the list `[x, y ,z]` converts to:
```COBOL
01 list1 pic x(4) occurs 3.
...
move "x" to list1(1)
move "y" to list1(2)
move "z" to list1(3)
```

If list is nested:
```COBOL
01 list1 pic x(4) occurs 3 typedef.
01 list2 list1 occurs 3.
```

**Tuple**: Translates to table. `(x, y, z)`:
```COBOL
01 tpl.
   03 x pic x(4).
   03 y pic x(4).
   03 z pic x(4).
...
move "x" to x of tpl. 
move "y" to y of tpl. 
move "z" to z of tpl. 
```

**Dictionary**: Translates to a table. Dictionary `{"key1": val1, "key2": val2}` translates to:

```COBOL
01 dict.
   03 key1 pic x(4).
   03 key2 pic x(4).
...
move "val1" to key1
move "val2" to key2
```

**Function call**: Translates to a 'call'. So a function call `f(x, y z)` translates to:

```COBOL
call "f" using by value x, y, z
```

Think it should be ok to raise exceptions for:
- Nested dictionary
- List with more than two layers of nesting.

**Comment by MFJackH** [comment]
It looks like we can use the `test.py` program in the `dataset_builder` folder to test our translator 👍

**Comment by MFJackH** [comment]
It looks like the important paths through the `test.py` code are:
### Prompt Translation
`main() -> test_translate() -> generic_translator.translate_prompt_and_tests() -> generic_translator.translate_prompt()`

### Test Case Translation
`main() -> test_translate() -> generic_translator.translate_prompt_and_tests() -> generic_translator.translate_tests()`

When translating tests, each test gets parsed using `ast.parse()` and the resulting Abstract Syntax Tree is walked, with each node having the `translate_expr()` function invoked on it. This invokes the translator functions we will implement.

### Tree Walking
We may need to modify how the test AST gets walked in order to generate a valid COBOL program, because:
- Variables have to be declared in the working storage section before they can be used.
- Any scenarios in python test cases where the return value of a function call is used will have to be adjusted for COBOL
  + For example, `if foo() != None:` would need to special consideration, possibly converted to something like:
```COBOL
*> Here foo places its return value in bar, with bar being declared in the Working Storage section
perform foo 
if ws-bar not = null
    *> Do the thing
end-if
```
or 
```COBOL
*> Here foo places its return value in bar, with bar being declared in the Working Storage section
call foo returning ws-bar
if ws-bar not = null
    *> Do the thing
end-if
```

**Comment by MFJackH** [comment]
# Tasks Remaining

## Remaining Data Structures
+ [ ] Tuples
+ [ ] Dicts

## Equality
  - [ ] Lists
  - [ ] Tuples
  - [ ] Dictionary

## Prompt 
+ [x] Add return type to procedure division
+ [ ] Adjust prompt to use `call` statements rather than function invocations

## Improvements
+ [ ] Improve list initialisation to use `perform varying` rather than `move value to list-n(m)`
+ [ ] Use linkage items for equality checking so we don't need to generate sections for every list instance
